### ISSUE TITLE
Is it compatible with Neo and Architect?

### ISSUE THREAD

**Issue by jmverges** [wbrowar/craft-grid#10]
Hi,

I was wondering if this is compatible or will be compatible with Neo and Architect. 

Thanks

**Comment by wbrowar** [comment]
Hi, @jmverges. Grid only supports Craft’s first party fields when you’re using the Target Field setting. However, you can use a grid field to lay out anything that can be formatted as an array. So you could use it with Neo if you can manually add items to the grid field, like this: https://github.com/wbrowar/craft-grid#using-grid-without-a-target-field

As far as Architect goes, I haven't tried importing or exporting grid fields with it, yet. It’s settings do work with Project Config, though.

**Comment by jmverges** [comment]
@wbrowar thanks for the answer I will be trying that. 

I found Architect an interesting option for managing Neo blocks with coding instead of drag and dropping into the CMS. Also for creating packages to reuse those blocks between installations. Wondering if the I could have a set of different Grid configurations and move those from 1 project to another.
