### ISSUE TITLE
Unused matrix block error.

### ISSUE THREAD

**Issue by Geestig** [wbrowar/craft-grid#11]
When adding a Matrix block but not using it in the grid field, I get an 'Undefined offset' error on save.

![image](https://user-images.githubusercontent.com/9035369/66033208-1583c600-e507-11e9-973d-41f5b397c8f7.png)

I'll see if I can find a fix for this when I got the time.

EDIT: Found a fix: Simply check that an item is not empty.

PART 1: LINE 234 -> 245 in Grid.php
 ```
if (!empty($targetIds[$i])) {
   $targetId = intval($targetIds[$i]);
   $valueId = $value['target']['items'][$i]['id'];

    if ($targetId != $valueId) {
       $unmatchedIds[] = [
             'target' => $targetId,
             'value' => $valueId,
           ];
      $value['target']['items'][$i]['id'] = $targetId;
   }
}
```

PART 2: LINE 315 -> 319
```
 if (!empty($fieldValue['target']['items'][$i])) {
  if ($breakpoint['id' . $fieldValue['target']['items'][$i]['id']] ?? false) {
      $breakpoint['id' . $currentIds[$i]] = $breakpoint['id' . $fieldValue['target']['items'][$i]['id']];
      unset($breakpoint['id' . $fieldValue['target']['items'][$i]['id']]);
  }
}
```

**Comment by wbrowar** [comment]
Thanks for both reporting and helping to figure this out, @Geestig! I'll have an update out in just a little bit with this fix in it.

**Comment by Geestig** [comment]
EDIT: New error. When adding a matrix block inbetween other blocks in the data matrix it returns an error because of the id not being found. @wbrowar
