### ISSUE TITLE
input list should be sticky.

### ISSUE THREAD

**Issue by Geestig** [wbrowar/craft-grid#17]
When looking at the code in the backend I see you've added position sticky to the items list. However this does not seem to work.

The reason for this is because on '.grid__input__breakpoints' you've added an overflow:hidden.

EDIT: Change your CSS with 'css control panel' (https://plugins.craftcms.com/cp-css) or something to the following for your lists to be sticky again.

```
.grid__input__breakpoints {
  overflow: visible !important;
}

.grid__input__breakpoint--before, .grid__input__breakpoint--after {
  opacity: 0 !important;
  transition: 0.2s all ease-out !important;
}
```

**Comment by wbrowar** [comment]
Thanks, @Geestig! I'll add this to the 3.5 compatibility update.
